### ISSUE TITLE
Tangnano 9K

### ISSUE THREAD

**Issue by kzali** [multigcs/LinuxCNC-RIO#10]
Oliver I just noticed that Tangnano 9k has been removed from this repository!  Was there a few days back any chance for it being redone?

**Comment by multigcs** [comment]
https://github.com/multigcs/LinuxCNC-RIO/tree/main/configs/TangNano9K

**Comment by kzali** [comment]
Sorry my fault

**Comment by multigcs** [comment]
no problem, it is a bit confusing because in the output folder there are only a few examples and for each config
