### ISSUE TITLE
unable to reset E-STOP

### ISSUE THREAD

**Issue by TurBoss** [multigcs/LinuxCNC-RIO#2]
Hello,

I'm trying to get the linuxcnc configs to run with the icebreaker board, but I'm unable to reset the E-STOP

I get this error: `Bad SPI payload = 32303a30`

Thanks

**Comment by multigcs** [comment]
does the ID change every time you try ?

i think this is a problem with SPI.
you can try to set the SPI-divider to 256 in rio.c:

    //bcm2835_spi_setClockDivider(BCM2835_SPI_CLOCK_DIVIDER_256);
    bcm2835_spi_setClockDivider(BCM2835_SPI_CLOCK_DIVIDER_128);

**Comment by TurBoss** [comment]
I think that is a bad setting in my board config clock speed, need to figure..

I tried changing that setting to 256 but this time got a different code in the message

**Comment by multigcs** [comment]
strange if it's work with the python tool
if you changed the firmware, you have also to update the rio.h and recompile the hal-component.

**Comment by multigcs** [comment]
ahh, and you need min. one Joint, one DIN, DOUT, VIN and VOUT until i have a fix for the hal-component

**Comment by TurBoss** [comment]
hello, 

i could not get it to work 
each time i press e-stop i get a different payload

**Comment by multigcs** [comment]
I don't know what I could improve at this point.
I think it is a connection problem, maybe too long cable or too high spi speed.

**Comment by TurBoss** [comment]
I'll check wiring 

thanks

**Comment by multigcs** [comment]
changing rio.c to 
  bcm2835_spi_setClockDivider(BCM2835_SPI_CLOCK_DIVIDER_256);
and recompile

does not help ?

**Comment by TurBoss** [comment]
Hello,

I tried soldering some headers to a PCB and got it like before, the qt app works but not linuxcnc,
I  tried changing that option in rio.c and recompile with halcompile  but got different payload errors 

:)

**Comment by multigcs** [comment]
:( hmm stange, can you send me your config please ?

**Comment by TurBoss** [comment]
sure here it is:

```json
{
    "name": "ICEBreakerV1.0e",
    "description": "Small and low cost FPGA educational and development board",
    "toolchain": "icestorm",
    "family": "ice40",
    "type": "up5k",
    "package": "sg48",
    "clock": {
        "speed": "120000000",
        "pin": "35"
    },
    "interface": [
    	{
	        "type": "spi",
	        "pins": {
	            "MOSI": "42",
	            "MISO": "43",
	            "SCK": "38",
	            "SEL": "36"
	        }
    	}
   ],
    "din": [
        {
            "debounce": true,
            "pin": "10"
        },
        {
            "debounce": true,
            "pin": "20"
        },
        {
            "debounce": true,
            "pin": "19"
        },
        {
            "debounce": true,
            "pin": "18"
        }
    ],
    "dout": [
        {
            "pin": "23"
        },
        {
            "pin": "25"
        },
        {
            "pin": "26"
        },
        {
            "pin": "21"
        },
        {
            "pin": "27"
        }
    ],
    "vin": [
        {
            "type": "frequency",
            "pin": "44",
            "pullup": true
        }
    ],
    "vout": [
        {
            "type": "pwm",
            "pin": "37",
            "invert_pwm": true
        },
        {
            "type": "pwm",
            "pin": "11",
            "invert_pwm": true
        }
    ],
    "joints": [
        {
            "comment": "J9.1+3+4",
            "type": "stepper",
            "cl": false,
            "pins": {
                "dir": "3",
                "step": "4",
                "enable": "48"
            }
        },
        {
            "comment": "J9.1+3+4_2",
            "type": "stepper",
            "cl": false,
            "pins": {
                "dir": "2",
                "step": "46",
                "enable": "47"
            }
        },
        {
            "comment": "J9.1+3+4_3",
            "type": "stepper",
            "cl": false,
            "pins": {
                "dir": "32",
                "step": "34",
                "enable": "28"
            }
        }
    ]
}

```

**Comment by multigcs** [comment]
Hmm, looks ok , this should generate a working rio.h file

**Comment by TurBoss** [comment]
hello,

I noticed having one more zero in the clock speed... :(

but if I configure 3 DOUT the python tool moves one more that is not in the json conf :/


![Screenshot_2023-05-29_07-52-25](https://github.com/multigcs/LinuxCNC-RIO/assets/184088/5a4a6c25-5051-4264-ab6b-aba1aeb44f5c)

Thanks

**Comment by multigcs** [comment]
I have update the tool a little bit, it's really bad but is helpful for testing :)

Ahh, Ok, so you have a clock of 12Mhz ?
maybe to slow for the fast SPI clock in the hal-component, but no problem (i hope):
`
    "clock": {
        "osc": "12000000",
        "speed": "50000000",
        "pin": "P6"
    },
`
the 'osc' ist you real clock speed and the 'speed' option is what you want to have,
this acitvates the internal PLL to push the clock speed up.

I think 50Mhz is ok, but you can also try 100Mhz

**Comment by TurBoss** [comment]
If I add the osc option i get this error

```

(venv) turboss@raspberrypi:~/LinuxCNC-RIO $ make
python3 buildtool.py configs/ICEBreakerV1.0e/config.json
generating files in Output/ICEBreakerV1.0e
generating linux-cnc config
generating linux-cnc component
generating firmware
generating qtgui
generating doc
(cd Output/ICEBreakerV1.0e/Firmware/ ; make)
make[1]: Entering directory '/home/turboss/LinuxCNC-RIO/Output/ICEBreakerV1.0e/Firmware'
yosys -q -l yosys.log -p 'synth_ice40 -top rio -json rio.json' vout_pwm.v vin_frequency.v quad_encoder.v joint_stepper.v joint_stepper_nf.v interface_spislave.v debouncer.v pll.v rio.v
nextpnr-ice40 -q -l nextpnr.log --up5k --package sg48 --json rio.json --pcf pins.pcf --asc rio.asc
ERROR: PLL 'mypll.uut' couldn't be placed anywhere, no suitable BEL found. Did you mean to use a PAD PLL ?
    PLL bel 'X12/Y31/pll_3' cannot be used as it conflicts with input 'sysclk_in$sb_io' on pin '35'.

ERROR: Packing design failed.
0 warnings, 2 errors
make[1]: *** [Makefile:12: rio.asc] Error 255
make[1]: Leaving directory '/home/turboss/LinuxCNC-RIO/Output/ICEBreakerV1.0e/Firmware'
make: *** [Makefile:39: firmware] Error 2
(venv) turboss@raspberrypi:~/LinuxCNC-RIO $

```

I'm very new to FPGA :)

Thank you

**Comment by multigcs** [comment]
ok, thats also new too me, my oss-cad-suite is a little bit to old and iceppl is missing parameter (-p).
I have add a newer version of icepll (files/icepll) and add an exception to the firmware generator,
hope this will now work for this case.
Please try it again

**Comment by TurBoss** [comment]
I run he build from the pi itself

now got this one :)

```
python3 buildtool.py configs/ICEBreakerV1.0e/config.json
generating files in Output/ICEBreakerV1.0e
generating linux-cnc config
generating linux-cnc component
generating firmware
sh: 1: files/icepll: Exec format error
generating qtgui
generating doc
```

**Comment by multigcs** [comment]
aaaa, sorry, new update :) i have running 2 versions on my system, the one in the oss-cad-suite works fine.

You are running direct on the raspberry, i build it for amd64, sorry

**Comment by TurBoss** [comment]
okay got this and looks like what i had in config
![image](https://github.com/multigcs/LinuxCNC-RIO/assets/184088/6deefee7-3cb9-48e1-9252-75856e017a93)

but still no way to get the estop out :/ the other time that got followin errors was becouse i commented that on hal :/

**Comment by multigcs** [comment]
i don't think it makes a different on  PC

**Comment by multigcs** [comment]
in binary, it looks like a speed issue:
0x32303a30  00110010001100000011101000110000
0x64617461   01100100011000010111010001100001

can you try to set the speed again:

* after building
* edit rio.h
* set: #define SPI_SPEED BCM2835_SPI_CLOCK_DIVIDER_2048 
* halcompile --install rio.c

and restart linuxcnc

this will slow down the spi speed to under 1Mhz

**Comment by multigcs** [comment]
and only to be sure, you have to stop the python tool if you running linuxcnc

**Comment by TurBoss** [comment]
yes yes only one app at time

**Comment by multigcs** [comment]
i have ordered an icebreaker board in china, hopefully in 2 weeks i will know more :)

**Comment by TurBoss** [comment]
don't worry I'm having lots of fun

**Comment by TurBoss** [comment]
I found the issue


may fault by having a offset in the iceprog tool 

big face palm :=)

can I set this as fixed :D


Thank you so much :D

**Comment by multigcs** [comment]
Wait what ?
does it work now ?

**Comment by TurBoss** [comment]
yes it does

i was had an offset of 1M in the iceprog from another project and forgot to remove :_)

Just finished soldering the protoboard I'll try to get a video

**Comment by multigcs** [comment]
cooool !!!!

**Comment by TurBoss** [comment]
here a short long video :D

https://www.youtube.com/watch?v=58RNJSGD0qs

**Comment by multigcs** [comment]
Very cool, thank you !

and i like your GUI, have to test it
