### ISSUE TITLE
joint_pwmdir does not generate pwm output

### ISSUE THREAD

**Issue by festlv** [multigcs/LinuxCNC-RIO#27]
I'm trying to use joint_pwmdir on ECP5. I've fixed one issue with enable signal (see pull request), but there still appears to be an issue with generated pwm signal.

Test setup:
Colorlight i5 dev board with custom +/-10V amplifier board
W32_ETH UDP2SPI bridge
qt_spitest.py for testing

Config.json: https://gist.github.com/festlv/ea4236ac91a1b3c0b6d7317be0bbccfa

Observations:
EN signal goes high as soon as test client connects.
DIR signal works correctly: it's high when pwm output is non-negative, and low when the output is positive.
PWM signal goes high whenever PWM output is non-zero (that is: it's low when joint output is 0 and high whenever there's any output).

**Comment by multigcs** [comment]
fixed, problem was the missing calculation for pwmout in qtgui.py

**Comment by festlv** [comment]
Cool, thanks! Will test my hw further!

**Comment by festlv** [comment]
Can confirm that the issue is fixed, pwmdir is being output correctly
