### ISSUE TITLE
Reverse output pwm

### ISSUE THREAD

**Issue by Nvems** [multigcs/LinuxCNC-RIO#36]
Hi.
Is there any way to set ouput pwm reverse
0% = 3.3v and 100% = 0V

I try json in example with invert= true
The ouput still 0%=0v , 100%= 3.3V

**Comment by multigcs** [comment]
please try:
```
"invert_pwm": true,
```

sorry, a little bit confusing :(

**Comment by Nvems** [comment]
Oh, yes it work
Thanks you
