### ISSUE TITLE
Creating digital inputs HAL: ERROR: pin_new(pinname) called with already-initialized memory

### ISSUE THREAD

**Issue by ozzyrob** [multigcs/LinuxCNC-RIO#8]
Was trying to create a config with 17 inputs was getting an error when loading the rio mudule.

HAL: ERROR: pin_new(_pinname_) called with already-initialized memory

Tracked it down to here
```
    for (bn = 0; bn < DIGITAL_INPUT_BYTES; bn++) {
        for (n = 0; n < 8; n++) {
            retval = hal_pin_bit_newf(HAL_OUT, &(data->inputs[bn * 8 + n * 2]), comp_id, "%s.input.%01d", prefix, bn * 8 + n);
            if (retval != 0) goto error;
            *(data->inputs[bn * 8 + n * 2]) = 0;
            retval = hal_pin_bit_newf(HAL_OUT, &(data->inputs[bn * 8 + n * 2 + 1]), comp_id, "%s.input.%01d-not", prefix, bn * 8 + n);
            if (retval != 0) goto error;
            *(data->inputs[bn * 8 + n * 2 + 1]) = 1;
}
```

This fix seemed to work: The added printfs were to see the difference in formula
```
    for (bn = 0; bn < DIGITAL_INPUT_BYTES; bn++) {
        for (n = 0; n < 8; n++) {
            //printf("Pin name: rio.pin-%02d-in @ mem %02d\n ",bn*8+n,(bn*8+n)*2);
            //printf("Pin name: rio.pin-%02d-in @ mem %02d\n ",bn*8+n,bn*8+n*2);
            retval = hal_pin_bit_newf(HAL_OUT, &(data->inputs[ (bn * 8 + n) * 2 ]), comp_id, "rio.pin-%02d-in",bn * 8 + n);
            if (retval != 0) goto error;
            *(data->inputs[ (bn * 8 + n) * 2 ]) = 0;
            retval = hal_pin_bit_newf(HAL_OUT, &(data->inputs[ (bn * 8 + n) * 2 + 1 ]), comp_id, "rio.pin-%02d-in-not", bn * 8 + n);
            if (retval != 0) goto error;
            *(data->inputs[(bn * 8 + n) * 2 + 1]) = 1;
        }
```

Below is a session with the original code (I was messing around with pin names) as you can see memory locations are duplicated 
halcmd: loadrt rio
Note: Using POSIX realtime
Pin name: rio.pin-00-in @ mem 00
 Pin name: rio.pin-01-in @ mem 02
 Pin name: rio.pin-02-in @ mem 04
 Pin name: rio.pin-03-in @ mem 06
 Pin name: rio.pin-04-in @ mem 08
 Pin name: rio.pin-05-in @ mem 10
 Pin name: rio.pin-06-in @ mem 12
 Pin name: rio.pin-07-in @ mem 14
 Pin name: rio.pin-08-in @ mem 08
HAL: ERROR: pin_new(rio.pin-08-in) called with already-initialized memory
HAL: ERROR: pin_new(rio.pin-08-in-not) called with already-initialized memory
 Pin name: rio.pin-09-in @ mem 10
HAL: ERROR: pin_new(rio.pin-09-in) called with already-initialized memory
HAL: ERROR: pin_new(rio.pin-09-in-not) called with already-initialized memory
 Pin name: rio.pin-10-in @ mem 12
HAL: ERROR: pin_new(rio.pin-10-in) called with already-initialized memory
HAL: ERROR: pin_new(rio.pin-10-in-not) called with already-initialized memory
 Pin name: rio.pin-11-in @ mem 14
HAL: ERROR: pin_new(rio.pin-11-in) called with already-initialized memory
HAL: ERROR: pin_new(rio.pin-11-in-not) called with already-initialized memory
 Pin name: rio.pin-12-in @ mem 16
 Pin name: rio.pin-13-in @ mem 18
 Pin name: rio.pin-14-in @ mem 20
 Pin name: rio.pin-15-in @ mem 22
halcmd: 

I hope this makes sense.

**Comment by multigcs** [comment]
Thank you !!!!
